baseURL = 'https://example.org/'
title = 'Light and Salt Learning'
[module]
  [[module.imports]]
    path = "github.com/Tim-Quattrochi/curriculum/common-theme"
  [[module.imports]]
    path = "github.com/Tim-Quattrochi/curriculum/common-content"
    [[module.imports.mounts]]
      source = "content"
      target = "content/guides"

